modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Cave%20Spider%20Spawn"
logoFile="icon.png"

[[mods]]
modId="cavespiderspawn"
version="1.0"
displayName="Cave Spider Spawn"
displayURL="https://serilum.com/mod/cave-spider-spawn"
authors="Rick South"
description='''Adds a chance for cave spiders to spawn naturally instead of a spider.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.cavespiderspawn]]
    modId="collective"
    type="required"
    mandatory=true
    versionRange="[7.23,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cavespiderspawn]]
    modId="minecraft"
    type="required"
    mandatory=true
    versionRange="[1.20.2]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "cavespiderspawn_neoforge.mixins.json"